### ISSUE TITLE
A suggestion / 提个建议

### ISSUE THREAD

**Issue by dlc423** [stroke-input/stroke-input-android#13]
初次使用，感觉很不错，希望加点功能，收回键盘可以设个键位，还有复制剪贴功能，这个用得比较多。

**Comment by yawnoc** [comment]
多謝反映。

鍵盤空間不多，不知何處加個收回鍵。用系統反回按鈕，已經可以收回鍵盤，[建議用舊式「三按鈕導航」，而不用新 Android 「手勢導航」](https://support.google.com/android/answer/9079644?hl=zh-Hans)。

曾斟酌複製剪貼，同樣有空間不夠之嫌，決定留待系統之複製剪貼功能而已。

---

Thank you for the feedback.

There is not much space on the keyboard, so I don't know where I would put a retract key. Retracting the keyboard can already be achieved by using the system Back Button; [I recommend the old-style "3-button navigation" rather than newer Android's "gesture navigation"](https://support.google.com/android/answer/9079644?hl=en).

I have pondered cut/copy/paste, and again there is the matter of insufficient room. So I have decided to leave that functionality up to the system.

**Comment by yawnoc** [comment]
@CRK1918 [v1.2.0](https://github.com/stroke-input/stroke-input-android/releases/tag/v1.2.0) 新增了鍵盤高度調整系數，上限原高度 1.5 倍。

---

[v1.2.0](https://github.com/stroke-input/stroke-input-android/releases/tag/v1.2.0) adds a keyboard height adjustment factor, up to 1.5 times the original height.
