### ISSUE TITLE
Help wanted in another program

### ISSUE THREAD

**Issue by GrimPixel** [stroke-input/stroke-input-android#14]
Hi! I found a program promising: [Thumb-Key](https://github.com/dessalines/thumb-key). It doesn't support CJKV currently, and is discussed in [an issue](https://github.com/dessalines/thumb-key/issues/99). Would you like to take a look?

**Comment by yawnoc** [comment]
Stroke Input Method, and, to my knowledge, any other Chinese input method, requires a candidates bar to display the candidates.

This is because:

1. Chinese characters are not sequences of letters.
2. There exist characters with the same encoding (e.g. 久凡丸夕夂夊 etc. are all 354 in strokes).

(Also in the special case of Stroke Input Method, you want to be able to type out common but many-stroke characters like 邊 without having to type out the entire sequence of its strokes.)

As far as I can tell, Thumb-Key is only designed for alphabetical languages where words are simply sequences of letters; there is no candidates bar to convert an encoding (e.g. a stroke sequence) into a Chinese character consistent with that encoding.

**Comment by GrimPixel** [comment]
Thank you for your reply.
That is already known. I found that program ideal to use and think if CJKV could be supported soon.
